server:
  port: 2001
  context-path: /

eureka:
  client:
    register-with-eureka: true #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone: http://localhost:3001/eureka/

  instance:
    instance-id: shop-customer:2001 #客户端实例名称
    prefer-ip-address: true #显示IP

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: shop-customer
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer

  redis:
    host: 192.168.199.234
    port: 6379
    password: foobared




